baseURL = "/"
title = "Law Reviews"
languageCode = "en-us"
timeZone = "America/New_York"

[build]
noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[build.buildStats]
enable = true

[outputs]
home = ["HTML", "RSS"]

[markup]
[markup.goldmark.renderer]
unsafe = true

[params]
description = "AI-powered document and matter intelligence for law firms."
author = "Lith Ltd"
copyright = "&copy; 2026 [Lith Ltd](https://lithltd.com)"
